import { useEffect, useMemo, useState } from 'react'
import api from '../services/api'
import { Link } from 'react-router-dom'

const statusTone = status => ['running', 'online', 'up'].includes(String(status).toLowerCase()) ? 'ui-status-badge--success' : ['stopped', 'offline', 'down'].includes(String(status).toLowerCase()) ? 'ui-status-badge--neutral' : 'ui-status-badge--warning'

export default function ProxmoxInventoryPage(){
  const [networks,setNetworks]=useState([]); const [storage,setStorage]=useState([])
  const [rows,setRows]=useState([]); const [templates,setTemplates]=useState([]); const [filters,setFilters]=useState({q:'',status:'',node:'',template:''})
  const [busy,setBusy]=useState(false); const [availability,setAvailability]=useState([]); const [isoSummary,setIsoSummary]=useState({items:[],warnings:[]}); const [message,setMessage]=useState(null)
  const load=async()=>{setBusy(true);setMessage(null);try{await api.post('/admin/proxmox/templates/sync');const[inv,disc,av,clusters]=await Promise.all([api.get('/admin/proxmox/inventory/vms'),api.get('/admin/proxmox/templates/discovered'),api.get('/admin/proxmox/templates/availability'),api.get('/admin/proxmox/clusters')]);setRows(Array.isArray(inv.data)?inv.data:[]);setTemplates(Array.isArray(disc.data)?disc.data:[]);setAvailability(Array.isArray(av.data)?av.data:[]);const active=(Array.isArray(clusters.data)?clusters.data:[]).find(cluster=>cluster.is_active);if(active?.id){const [iso,net,stores]=await Promise.all([api.get(`/admin/proxmox/clusters/${active.id}/isos`),api.get(`/admin/proxmox/clusters/${active.id}/networks`),api.get(`/admin/proxmox/clusters/${active.id}/storage`)]);setNetworks(net.data||[]);setStorage(stores.data||[]);setIsoSummary({items:iso?.data?.items||[],warnings:iso?.data?.warnings||[]})}else setIsoSummary({items:[],warnings:['No active cluster for ISO/media discovery.']})}catch(error){setMessage({type:'error',text:JSON.stringify(error?.response?.data?.detail||error.message)})}finally{setBusy(false)}}
  useEffect(()=>{load()},[])
  const filtered=useMemo(()=>rows.filter(row=>(!filters.status||row.status===filters.status)&&(!filters.node||row.node===filters.node)&&(!(filters.template==='templates')||row.template)&&(!(filters.template==='vms')||!row.template)&&(!filters.q||(String(row.name||'').toLowerCase().includes(filters.q.toLowerCase())||String(row.vmid).includes(filters.q)))),[rows,filters])
  const nodes=[...new Set(rows.map(row=>row.node).filter(Boolean))]; const statuses=[...new Set(rows.map(row=>row.status).filter(Boolean))]

  return <section className='page-shell' aria-labelledby='inventory-title'>
    <header className='ui-page-header'><div className='ui-page-header__copy'><p className='muted'>Infrastructure</p><h2 id='inventory-title' className='ui-page-header__title'>Proxmox inventory</h2><p className='ui-page-header__description'>Discover VMs, templates, networks, storage and media from your active cluster. Templates join this organization’s catalog automatically.</p></div><div className='ui-page-header__actions'><button disabled={busy} onClick={load}>{busy?'Refreshing…':'Refresh'}</button><Link to='/templates'>Template catalog</Link></div></header>
    <p className='muted'>Manage provisioned lab VMs from the VMs page. Discovered infrastructure remains visible here without changing ownership.</p>
    {busy ? <p role='status'>Refreshing cluster inventory…</p> : null}
    {message?<p className={`ui-alert ui-alert--${message.type}`} role={message.type==='error'?'alert':'status'} aria-live='polite'>{message.text}</p>:null}
    <section className='ui-card' aria-labelledby='inventory-filter-title'><h3 id='inventory-filter-title'>Filter inventory</h3><div className='ui-form-grid'><label className='ui-field'>Name or VMID<input className='input' type='search' value={filters.q} onChange={event=>setFilters({...filters,q:event.target.value})}/></label><label className='ui-field'>Node<select className='input' value={filters.node} onChange={event=>setFilters({...filters,node:event.target.value})}><option value=''>All nodes</option>{nodes.map(node=><option key={node}>{node}</option>)}</select></label><label className='ui-field'>Status<select className='input' value={filters.status} onChange={event=>setFilters({...filters,status:event.target.value})}><option value=''>All statuses</option>{statuses.map(status=><option key={status}>{status}</option>)}</select></label><label className='ui-field'>Resource type<select className='input' value={filters.template} onChange={event=>setFilters({...filters,template:event.target.value})}><option value=''>VMs and templates</option><option value='templates'>Templates only</option><option value='vms'>VMs only</option></select></label></div></section>
    <details className='ui-card' open><summary><strong>Discovered templates</strong> · {templates.length}</summary><p className='muted'>ISO/media discovered: {isoSummary.items.length}{isoSummary.warnings.length?` · ${isoSummary.warnings.join('; ')}`:''}</p>{templates.length===0&&!busy&&!message?<p className='muted'>No templates were discovered.</p>:<div className='ui-table-wrap' role='region' aria-label='Discovered templates' tabIndex='0'><table className='ui-table'><thead><tr><th scope='col'>VMID</th><th scope='col'>Name</th><th scope='col'>Node</th><th scope='col'>Imported</th><th scope='col'>Available nodes</th></tr></thead><tbody>{templates.map(template=>{const available=availability.find(item=>Number(item.template_vmid)===Number(template.vmid));return <tr key={`${template.node}-${template.vmid}`}><td>{template.vmid}</td><th scope='row'>{template.name}</th><td>{template.node}</td><td>{template.already_imported?'Yes':'No'}</td><td>{available?(available.available_nodes||[]).join(', '):'—'}{available?.warnings?.length?<div className='muted'>{available.warnings.join('; ')}</div>:null}{available?.recommended_action?<div className='muted'>{available.recommended_action}</div>:null}</td></tr>})}</tbody></table></div>}</details>
    <section className='ui-card' aria-labelledby='all-inventory-title'><div className='ui-card__header'><div><h3 id='all-inventory-title'>All VMs and templates</h3><p className='ui-card__description'>{filtered.length} of {rows.length} resources shown</p></div></div>{!busy&&!message&&filtered.length===0?<p className='muted'>No resources match the current filters.</p>:<div className='ui-table-wrap' role='region' aria-labelledby='all-inventory-title' tabIndex='0'><table className='ui-table'><thead><tr><th scope='col'>Node</th><th scope='col'>VMID</th><th scope='col'>Name</th><th scope='col'>Status</th><th scope='col'>Template</th><th scope='col'>Linked</th><th scope='col'>Owner</th></tr></thead><tbody>{filtered.map(row=><tr key={`${row.node}-${row.vmid}`}><td>{row.node}</td><td>{row.vmid}</td><th scope='row'>{row.name}</th><td><span className={`ui-status-badge ${statusTone(row.status)}`}>{row.status||'unknown'}</span></td><td>{row.template?'Yes':'No'}</td><td>{row.app_linked?'Yes':'No'}</td><td>{row.owner_username||'-'}</td></tr>)}</tbody></table></div>}</section>

    <section className='ui-card' aria-labelledby='network-storage-title'><h3 id='network-storage-title'>Networks and storage</h3><div className='card-grid'><div><h4>VM bridges</h4>{networks.map((net,index)=><p key={index}>{net.node} · {net.bridge} · {net.active ? 'Active' : 'Inactive'}</p>)}</div><div><h4>Storage pools</h4>{storage.map((store,index)=><p key={index}>{store.node} · {store.storage} · {store.type} · {store.active ? 'Active' : 'Inactive'}</p>)}</div></div>{!busy&&!message&&!networks.length&&!storage.length?<p>No networks or storage were discovered.</p>:null}</section>
    <section className='ui-card' aria-labelledby='media-title'><h3 id='media-title'>Installation media</h3>{isoSummary.items.map((item,index)=><p key={index}>{item.node} · {item.storage} · {item.volid || item.name || 'Media'}</p>)}{!busy&&!message&&!isoSummary.items.length?<p>No installation media was discovered.</p>:null}</section>
  </section>
}
